name: Docker image build
on:
  workflow_dispatch:
  workflow_call:
#    inputs:
#      dockerhub_username:
#        required: true
#        type: string
#      dockerhub_token:
#        required: true
#        type: string

jobs:
  docker_image:
    name: Create and push docker image
    runs-on: ubuntu-22.04

    steps:

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
#          username: ${{ inputs.dockerhub_username }}
#          password: ${{ inputs.dockerhub_token }}
