name: Test
on:
  workflow_call:
  workflow_dispatch:
  push:
    branches-ignore:
      - main
  pull_request:
    branches:
      - main

jobs:
  echo_rep_n:
    name: Test triggers
    runs-on: ubuntu-22.04
    steps:
      - name: Test triggers
        run: echo "The name of the docker image is ${{ github.repository }}"
